# Generated by Django 3.0.4 on 2020-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200403_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsai',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
    ]
