# Generated by Django 3.0.4 on 2020-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200406_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsai',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
